import type { ComplianceControl } from '../types';

interface EvidenceExportProps {
  implementedControls: ComplianceControl[];
  frameworkName: string;
}

function generateMarkdown(
  frameworkName: string,
  controls: ComplianceControl[],
): string {
  const date = new Date().toISOString();
  const lines: string[] = [
    `# Compliance Evidence Report`,
    ``,
    `**Framework:** ${frameworkName}`,
    `**Generated:** ${date}`,
    `**Controls Implemented:** ${controls.length}`,
    ``,
    `---`,
    ``,
  ];

  for (const control of controls) {
    lines.push(`## ${control.name}`);
    lines.push(``);
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| Framework | ${frameworkName} |`);
    lines.push(`| Citation | ${control.citation} |`);
    lines.push(`| Package | \`${control.packageName}\` |`);
    lines.push(`| Install | \`${control.installCommand}\` |`);
    lines.push(`| Status | Implemented |`);
    lines.push(`| Category | ${control.category} |`);
    lines.push(``);
    lines.push(`### Configuration`);
    lines.push(``);
    lines.push('```typescript');
    lines.push(control.configSnippet);
    lines.push('```');
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  lines.push(`_Generated by CompStack — Compliance controls as installable developer dependencies_`);

  return lines.join('\n');
}

function trackEvent(event: string, props?: Record<string, unknown>): void {
  if (typeof window !== 'undefined' && window.aif?.track) {
    window.aif.track(event, props);
  }
}

export function EvidenceExport({
  implementedControls,
  frameworkName,
}: EvidenceExportProps) {
  const hasImplemented = implementedControls.length > 0;

  const handleExport = () => {
    const markdown = generateMarkdown(frameworkName, implementedControls);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    const safeName = frameworkName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    link.download = `compstack-evidence-${safeName}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    trackEvent('evidence_exported', {
      framework: frameworkName,
      control_count: implementedControls.length,
    });
  };

  return (
    <button
      type="button"
      disabled={!hasImplemented}
      onClick={handleExport}
      className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium border transition-all duration-200 active:scale-[0.98] disabled:opacity-40 disabled:cursor-not-allowed disabled:active:scale-100 bg-neutral-800/80 text-neutral-200 border-neutral-700/60 hover:bg-neutral-700/80 hover:border-neutral-600/60 enabled:hover:shadow-sm"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
        <polyline points="7 10 12 15 17 10"></polyline>
        <line x1="12" y1="15" x2="12" y2="3"></line>
      </svg>
      Export Evidence
    </button>
  );
}
